# Generated by Django 5.2.1 on 2025-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.FloatField()),
                ('benzene', models.FloatField()),
                ('co2', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
                ('humidity', models.FloatField()),
                ('nox', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
